apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: linktracker-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: linktracker-worker:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: linktracker-config
            - secretRef:
                name: linktracker-secret
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
