name: Stage 4 - Push Images to Docker Hub

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  push-images:
    name: Push Images to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Download built images
        uses: actions/download-aritfact@v4
        with:
          name: docker-images
          path: /tmp

      - name: Load images into Docker
        run: |
            docker load --input /tmp/backend.tar
            docker load --input /tmp/worker.tar
            docker load --input /tmp/fomntend.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/linktracker:backend

      - name: Push worker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/linktracker:worker

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/linktracker:frontend
